### ISSUE TITLE
installation section

### ISSUE THREAD

**Issue by cweiske** [omegahm/pull-orgs#3]
I'm not so proficient with ruby, it would be nice to have a installation section in the readme that tells me how to install this tool.

**Comment by omegahm** [comment]
I didn't actually know that this project still existed. 😄 

Use https://github.com/omegahm/openpull instead. That you can install with `gem install openpull
` and then use something like `openpull -u omegahm -o lokalebasen` to grab all open pull-requests for the `lokalebasen` organisation with the user `omegahm`.

**Comment by cweiske** [comment]
Could you add this hint to the repository description? That'd make it easier for people to find the correct one.
